/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRefreshVintedRouteImport } from './routes/_admin/refresh-vinted'
import { Route as AdminRefreshMondialrelayRouteImport } from './routes/_admin/refresh-mondialrelay'
import { Route as AdminRefreshChronopostRouteImport } from './routes/_admin/refresh-chronopost'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as ApiPublicRefreshPudosRouteImport } from './routes/api/public/refresh-pudos'
import { Route as ApiPublicHooksEnrichVintedGoRouteImport } from './routes/api/public/hooks/enrich-vinted-go'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefreshVintedRoute = AdminRefreshVintedRouteImport.update({
  id: '/_admin/refresh-vinted',
  path: '/refresh-vinted',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefreshMondialrelayRoute =
  AdminRefreshMondialrelayRouteImport.update({
    id: '/_admin/refresh-mondialrelay',
    path: '/refresh-mondialrelay',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRefreshChronopostRoute = AdminRefreshChronopostRouteImport.update({
  id: '/_admin/refresh-chronopost',
  path: '/refresh-chronopost',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/_admin/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshPudosRoute = ApiPublicRefreshPudosRouteImport.update({
  id: '/api/public/refresh-pudos',
  path: '/api/public/refresh-pudos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEnrichVintedGoRoute =
  ApiPublicHooksEnrichVintedGoRouteImport.update({
    id: '/api/public/hooks/enrich-vinted-go',
    path: '/api/public/hooks/enrich-vinted-go',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/refresh-chronopost': typeof AdminRefreshChronopostRoute
  '/refresh-mondialrelay': typeof AdminRefreshMondialrelayRoute
  '/refresh-vinted': typeof AdminRefreshVintedRoute
  '/api/public/refresh-pudos': typeof ApiPublicRefreshPudosRoute
  '/api/public/hooks/enrich-vinted-go': typeof ApiPublicHooksEnrichVintedGoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/refresh-chronopost': typeof AdminRefreshChronopostRoute
  '/refresh-mondialrelay': typeof AdminRefreshMondialrelayRoute
  '/refresh-vinted': typeof AdminRefreshVintedRoute
  '/api/public/refresh-pudos': typeof ApiPublicRefreshPudosRoute
  '/api/public/hooks/enrich-vinted-go': typeof ApiPublicHooksEnrichVintedGoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/refresh-chronopost': typeof AdminRefreshChronopostRoute
  '/_admin/refresh-mondialrelay': typeof AdminRefreshMondialrelayRoute
  '/_admin/refresh-vinted': typeof AdminRefreshVintedRoute
  '/api/public/refresh-pudos': typeof ApiPublicRefreshPudosRoute
  '/api/public/hooks/enrich-vinted-go': typeof ApiPublicHooksEnrichVintedGoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/refresh-chronopost'
    | '/refresh-mondialrelay'
    | '/refresh-vinted'
    | '/api/public/refresh-pudos'
    | '/api/public/hooks/enrich-vinted-go'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/refresh-chronopost'
    | '/refresh-mondialrelay'
    | '/refresh-vinted'
    | '/api/public/refresh-pudos'
    | '/api/public/hooks/enrich-vinted-go'
  id:
    | '__root__'
    | '/'
    | '/_admin/dashboard'
    | '/_admin/refresh-chronopost'
    | '/_admin/refresh-mondialrelay'
    | '/_admin/refresh-vinted'
    | '/api/public/refresh-pudos'
    | '/api/public/hooks/enrich-vinted-go'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminRefreshChronopostRoute: typeof AdminRefreshChronopostRoute
  AdminRefreshMondialrelayRoute: typeof AdminRefreshMondialrelayRoute
  AdminRefreshVintedRoute: typeof AdminRefreshVintedRoute
  ApiPublicRefreshPudosRoute: typeof ApiPublicRefreshPudosRoute
  ApiPublicHooksEnrichVintedGoRoute: typeof ApiPublicHooksEnrichVintedGoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/refresh-vinted': {
      id: '/_admin/refresh-vinted'
      path: '/refresh-vinted'
      fullPath: '/refresh-vinted'
      preLoaderRoute: typeof AdminRefreshVintedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/refresh-mondialrelay': {
      id: '/_admin/refresh-mondialrelay'
      path: '/refresh-mondialrelay'
      fullPath: '/refresh-mondialrelay'
      preLoaderRoute: typeof AdminRefreshMondialrelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/refresh-chronopost': {
      id: '/_admin/refresh-chronopost'
      path: '/refresh-chronopost'
      fullPath: '/refresh-chronopost'
      preLoaderRoute: typeof AdminRefreshChronopostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-pudos': {
      id: '/api/public/refresh-pudos'
      path: '/api/public/refresh-pudos'
      fullPath: '/api/public/refresh-pudos'
      preLoaderRoute: typeof ApiPublicRefreshPudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/enrich-vinted-go': {
      id: '/api/public/hooks/enrich-vinted-go'
      path: '/api/public/hooks/enrich-vinted-go'
      fullPath: '/api/public/hooks/enrich-vinted-go'
      preLoaderRoute: typeof ApiPublicHooksEnrichVintedGoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminRefreshChronopostRoute: AdminRefreshChronopostRoute,
  AdminRefreshMondialrelayRoute: AdminRefreshMondialrelayRoute,
  AdminRefreshVintedRoute: AdminRefreshVintedRoute,
  ApiPublicRefreshPudosRoute: ApiPublicRefreshPudosRoute,
  ApiPublicHooksEnrichVintedGoRoute: ApiPublicHooksEnrichVintedGoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
